### ISSUE TITLE
Artifactory URL has changed in gradle.properties

### ISSUE THREAD

**Issue by StephenHarmon** [ptc-iot-sharing/SftpExtensionTWX#2]
The artifactory context URL in gradle.properties for ThingWorx dependencies used to be:
```
artifactory_contextUrl=http://twxcisvr.thingworx.com:8082/artifactory
```
That repo has been retired. The new URL should be:
```
artifactory_contextUrl=https://artifactory.rd2.thingworx.io/artifactory
```
I don't know what to do about credentials for non-PTC developers. That repo is secured. If there are restricted access credentials, like there were for the old repo, the following values would need to be updated, or instructions on how to authenticate would need to be provided.
```
artifactory_user=<username>
artifactory_password=<password>
```

**Comment by StephenHarmon** [comment]
According to the internal Jira issue announcing the change, the repo will no longer be available to the public. We may need to provide the files that were formerly downloaded as dependencies.

**Comment by stefan-lacatus** [comment]
Going to close this as addressed in https://github.com/ptc-iot-sharing/SftpExtensionTWX/commit/88303f40fedeb6f2d6abd5614e60cce1689afe45

Thanks for bringing it up.
